# Generated by Django 5.1.4 on 2025-01-10 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ciprojects'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIProjectsFiles',
            fields=[
                ('project_file_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField()),
                ('file_title', models.CharField(max_length=255)),
                ('attachment_file', models.FileField(upload_to='project_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ciprojects')),
            ],
        ),
    ]
