# Generated by Django 5.1.4 on 2025-01-10 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ciprojectsfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIProjectBugs',
            fields=[
                ('project_bug_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField()),
                ('bug_note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_bugs', to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_bugs', to='app.ciprojects')),
            ],
        ),
    ]
