# Generated by Django 5.1.4 on 2025-01-09 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiomatricDataTemp',
            fields=[
                ('biomatric_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.CharField(max_length=50)),
                ('login_date', models.CharField(db_column='login_date', default=datetime.datetime.today, max_length=100)),
                ('clock_in', models.CharField(max_length=100)),
                ('clock_in_location', models.CharField(max_length=100)),
                ('clock_out', models.CharField(max_length=100)),
                ('clock_out_location', models.CharField(max_length=100)),
                ('state_in_out', models.CharField(max_length=100)),
                ('late_mark', models.CharField(max_length=100)),
                ('early_mark', models.CharField(default='0', max_length=100)),
                ('total_work', models.CharField(default='0', max_length=100)),
                ('attendance_date', models.CharField(db_column='attendance_date', default=datetime.datetime.today, max_length=100)),
                ('attendance_status', models.CharField(db_column='attendance_status', default='Present', max_length=100)),
                ('status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('from_od', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=2)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('wfh', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
            ],
            options={
                'db_table': 'ci_biomatric_data',
                'managed': False,
            },
        ),
    ]
