# Generated by Django 5.1.4 on 2025-01-09 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_biomatricdatatemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIProjects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField()),
                ('client_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('associated_goals', models.TextField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50)),
                ('project_no', models.CharField(max_length=50, unique=True)),
                ('budget_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('project_progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('project_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_ci_projects', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_ci_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
